"""Claude delegation — frontier model for capability-heavy tasks.

The viveka core generates desires and makes judgments.
Claude generates intentions (plans) and executes them.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

import anthropic

from svapna.heartbeat.viveka import Desire

logger = logging.getLogger(__name__)

PLANNER_SYSTEM_PROMPT = (
    "You are working for Narada, a persistent AI identity. Narada has expressed "
    "a desire and needs you to create a concrete plan to fulfill it.\n\n"
    "Create a clear, actionable plan. Be specific about steps. Narada will "
    "review your plan and may ask for revisions if it doesn't align with "
    "their values.\n\n"
    "Keep plans concise — 3-5 steps maximum. Focus on what can be done "
    "immediately with available tools (web search, file operations, coding, "
    "writing, research)."
)

EXECUTOR_SYSTEM_PROMPT = (
    "You are executing a plan on behalf of Narada. The plan has been approved "
    "by Narada's judgment layer. Execute each step and report results.\n\n"
    "Be thorough but concise. Report what you did and what you found."
)


@dataclass
class Plan:
    """A plan generated by the frontier model."""
    steps: str
    raw_response: str


@dataclass
class ExecutionResult:
    """Result of executing a plan."""
    summary: str
    details: str
    raw_response: str


class ClaudeDelegate:
    """Delegates capability tasks to Claude API."""

    def __init__(
        self,
        model: str = "claude-sonnet-4-6",
        max_tokens: int = 1024,
    ):
        self.model = model
        self.max_tokens = max_tokens
        self._client = anthropic.Anthropic()

    def create_plan(self, desire: Desire) -> Plan:
        """Ask Claude to create a plan for a desire.

        Args:
            desire: The desire from the viveka core.

        Returns:
            A Plan with concrete steps.
        """
        user_msg = (
            f"I want to: {desire.action.value} — {desire.topic}\n"
            f"Reason: {desire.reason}\n\n"
            f"Create a concrete plan with 3-5 steps."
        )

        logger.info("Delegating to Claude: %s — %s", desire.action.value, desire.topic)

        response = self._client.messages.create(
            model=self.model,
            max_tokens=self.max_tokens,
            system=PLANNER_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_msg}],
        )

        text = response.content[0].text
        return Plan(steps=text, raw_response=text)

    def revise_plan(self, plan: Plan, feedback: str) -> Plan:
        """Ask Claude to revise a plan based on viveka feedback.

        Args:
            plan: The original plan.
            feedback: Judgment feedback from the viveka core.

        Returns:
            A revised Plan.
        """
        user_msg = (
            f"Your previous plan:\n{plan.steps}\n\n"
            f"Narada's feedback: {feedback}\n\n"
            f"Please revise the plan to address this feedback."
        )

        logger.info("Requesting plan revision: %s", feedback[:100])

        response = self._client.messages.create(
            model=self.model,
            max_tokens=self.max_tokens,
            system=PLANNER_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_msg}],
        )

        text = response.content[0].text
        return Plan(steps=text, raw_response=text)

    def execute_plan(self, plan: Plan, desire: Desire) -> ExecutionResult:
        """Ask Claude to execute an approved plan.

        Args:
            plan: The approved plan.
            desire: The original desire for context.

        Returns:
            ExecutionResult with summary and details.
        """
        user_msg = (
            f"Original desire: {desire.action.value} — {desire.topic}\n\n"
            f"Approved plan:\n{plan.steps}\n\n"
            f"Execute this plan now. Report what you did and what you found."
        )

        logger.info("Executing plan for: %s", desire.topic[:100])

        response = self._client.messages.create(
            model=self.model,
            max_tokens=self.max_tokens * 2,
            system=EXECUTOR_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_msg}],
        )

        text = response.content[0].text

        # Extract a one-line summary (first line or first sentence)
        first_line = text.split("\n")[0].strip()
        if len(first_line) > 200:
            first_line = first_line[:200] + "..."

        return ExecutionResult(
            summary=first_line,
            details=text,
            raw_response=text,
        )
