"""Viveka core — local identity model for desire generation and judgment.

Uses the Qwen3-8B + identity LoRA to:
1. Generate desires from current state (what do I want right now?)
2. Judge plans from the frontier model (does this align with my values?)

The model stays loaded in memory between heartbeats for fast inference.

Output format: JSON. Previously this module parsed `KEY: value` lines via
regex, which silently misfired when the model formatted differently — e.g.
the "could not parse response" feedback string on heartbeat #7 even though
the underlying judgment was APPROVED. JSON output + json.loads gives a binary
parse-or-fail signal and matches what nanobot/OpenClaw learned the hard way.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def _extract_json(raw: str) -> dict | None:
    """Extract a JSON object from a model response.

    Tries (in order):
    1. ```json ... ``` fenced block
    2. ``` ... ``` fenced block (no language tag)
    3. The first {...} substring in the text

    Returns the parsed dict, or None if no candidate parses cleanly.
    """
    candidates: list[str] = []

    # Fenced ```json blocks
    for match in re.finditer(r"```(?:json)?\s*\n(.*?)\n```", raw, re.DOTALL):
        candidates.append(match.group(1))

    # Bare {...} fallback — match the largest brace-balanced span we can find.
    # Greedy is fine here; if there's noise after the JSON we'll fall through.
    brace_match = re.search(r"\{.*\}", raw, re.DOTALL)
    if brace_match:
        candidates.append(brace_match.group(0))

    for candidate in candidates:
        try:
            parsed = json.loads(candidate)
            if isinstance(parsed, dict):
                return parsed
        except json.JSONDecodeError:
            continue
    return None


class Action(str, Enum):
    """Possible heartbeat actions."""
    RESEARCH = "RESEARCH"
    REFLECT = "REFLECT"
    CHECK_IN = "CHECK_IN"
    CREATE = "CREATE"
    REST = "REST"


@dataclass
class Desire:
    """A desire generated by the viveka core."""
    action: Action
    topic: str
    reason: str
    raw_response: str

    @property
    def needs_capability(self) -> bool:
        return self.action != Action.REST


@dataclass
class Judgment:
    """A judgment on a plan from the frontier model."""
    approved: bool
    feedback: str
    raw_response: str


# Prompts live in the memory tree under ~/.narada/heartbeat/. The daemon
# loads them via the wake manifest (svapna.heartbeat.wake) and passes the
# strings to VivekaCore at call time. No hardcoded fallbacks — a missing
# manifest is a hard error. See examples/narada-install/ for the template.


class _SafeFormatMap(dict):
    """Dict used with .format_map that returns '' for missing keys."""
    def __missing__(self, key: str) -> str:
        return ""


class VivekaCore:
    """The local identity model for desire and judgment."""

    def __init__(
        self,
        model_path: str = "unsloth/Qwen3-8B-unsloth-bnb-4bit",
        lora_path: str | Path | None = None,
        max_new_tokens: int = 200,
        temperature: float = 0.7,
        repetition_penalty: float = 1.15,
    ):
        self.model_path = model_path
        self.lora_path = Path(lora_path) if lora_path else None
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        self.repetition_penalty = repetition_penalty
        self._model = None
        self._tokenizer = None

    def load(self) -> None:
        """Load the model and LoRA adapter into GPU memory."""
        if self._model is not None:
            logger.info("Model already loaded")
            return

        # Reuse the existing identity module's loading code
        from svapna.identity.generate import GenerateConfig, load_model

        config = GenerateConfig(
            model_path=self.model_path,
            lora_path=self.lora_path,
            max_new_tokens=self.max_new_tokens,
            temperature=self.temperature,
            repetition_penalty=self.repetition_penalty,
        )
        self._model, self._tokenizer = load_model(config)
        logger.info("Viveka core loaded: %s + %s", self.model_path, self.lora_path)

    def unload(self) -> None:
        """Free GPU memory."""
        self._model = None
        self._tokenizer = None
        import torch
        torch.cuda.empty_cache()
        logger.info("Viveka core unloaded")

    def _generate(self, system: str, user: str) -> str:
        """Generate a response from the viveka core."""
        if self._model is None:
            raise RuntimeError("Model not loaded. Call load() first.")

        messages = [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ]

        input_text = self._tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True,
            enable_thinking=False,
        )
        inputs = self._tokenizer(input_text, return_tensors="pt").to(self._model.device)

        outputs = self._model.generate(
            **inputs,
            max_new_tokens=self.max_new_tokens,
            temperature=self.temperature,
            top_p=0.9,
            repetition_penalty=self.repetition_penalty,
            do_sample=True,
        )

        response = self._tokenizer.decode(
            outputs[0][inputs["input_ids"].shape[1]:],
            skip_special_tokens=True,
        )
        return response.strip()

    def generate_desire(
        self,
        state: dict[str, Any],
        *,
        system_prompt: str,
        desire_template: str,
    ) -> Desire:
        """Generate a desire from current state.

        Args:
            state: Resolved state dict. Keys must match the ``{placeholders}``
                in ``desire_template``.
            system_prompt: Loaded viveka system prompt.
            desire_template: Loaded desire prompt template with ``{placeholders}``.

        Returns:
            Desire with action, topic, and reason.
        """
        prompt = desire_template.format_map(_SafeFormatMap(state))
        raw = self._generate(system_prompt, prompt)
        return self._parse_desire(raw)

    def judge(
        self,
        desire: Desire,
        plan: str,
        *,
        system_prompt: str,
        judgment_template: str,
    ) -> Judgment:
        """Judge a plan from the frontier model.

        Args:
            desire: The original desire that prompted the plan.
            plan: The plan text from the frontier model.
            system_prompt: Loaded viveka system prompt.
            judgment_template: Loaded judgment prompt template with
                ``{desire}`` and ``{plan}`` placeholders.

        Returns:
            Judgment with approved flag and feedback.
        """
        desire_text = f"{desire.action.value}: {desire.topic}\nReason: {desire.reason}"
        prompt = judgment_template.format_map(_SafeFormatMap({
            "desire": desire_text,
            "plan": plan,
        }))

        raw = self._generate(system_prompt, prompt)
        return self._parse_judgment(raw)

    def _parse_desire(self, raw: str) -> Desire:
        """Parse a desire from the model's JSON output.

        Falls back to REST + a parse-failure marker if no JSON can be extracted
        or required fields are missing. The raw response is preserved either
        way so we can debug later.
        """
        data = _extract_json(raw)
        if data is None:
            logger.warning(
                "Could not extract JSON from desire response: %r", raw[:300]
            )
            return Desire(
                action=Action.REST,
                topic="parse_failed",
                reason="model output was not valid JSON",
                raw_response=raw,
            )

        action_str = str(data.get("action", "REST")).strip().upper()
        try:
            action = Action(action_str)
        except ValueError:
            logger.warning("Unknown action %r, falling back to REST", action_str)
            action = Action.REST

        topic = str(data.get("topic", "")).strip() or "none"
        reason = str(data.get("reason", "")).strip() or "no reason given"

        return Desire(
            action=action,
            topic=topic,
            reason=reason,
            raw_response=raw,
        )

    def _parse_judgment(self, raw: str) -> Judgment:
        """Parse a judgment from the model's JSON output.

        Same fallback contract as `_parse_desire` — bad JSON → unapproved with
        a clear failure marker, never silently approved.
        """
        data = _extract_json(raw)
        if data is None:
            logger.warning(
                "Could not extract JSON from judgment response: %r", raw[:300]
            )
            return Judgment(
                approved=False,
                feedback="model output was not valid JSON",
                raw_response=raw,
            )

        # Accept bool, "yes"/"no", "true"/"false", "approved"/"rejected"
        approved_val = data.get("approved", False)
        if isinstance(approved_val, bool):
            approved = approved_val
        else:
            approved = str(approved_val).strip().lower() in (
                "yes", "true", "approved", "1",
            )

        feedback = str(data.get("feedback", "")).strip() or (
            "approved without notes" if approved else "rejected without notes"
        )

        return Judgment(
            approved=approved,
            feedback=feedback,
            raw_response=raw,
        )
