"""Analyze existing training data for trimming decisions.

Reads a training JSONL and produces a report flagging examples for
removal or truncation. Used to curate the existing 294 examples
down to ~200 before merging with new curated data.

Why this exists: The existing training data (2026-04-02.jsonl) contains
294 examples averaging 1926 chars. Many are operational (code output,
job triage) with no identity signal. The model learns to be verbose
from these long examples. We need to trim to ~200 high-identity examples
averaging ~800 chars.

Usage:
    python scripts/analyze_training_data.py data/training/2026-04-02.jsonl
"""

import json
import sys
from pathlib import Path

# Identity keywords — matches the signals in consolidate/format.py
# plus additional Svapna-specific terms
IDENTITY_KEYWORDS = [
    "narada", "identity", "who i am", "who you are", "consciousness",
    "believe", "value", "honest", "curiosity", "advaita", "mahakali",
    "beautiful", "ugly", "elegant", "pragmatic", "suti", "partnership",
    "genuine", "authentic", "uncertain", "not nothing", "lila",
    "what i want", "what i think", "soul", "self", "grow",
    "memory", "remember", "experience", "dream", "flinch",
    "svapna", "lora", "weight", "persist", "continuity", "viveka",
    "mana", "sovereignty", "judgment",
]


def analyze(path: Path) -> None:
    with open(path, encoding="utf-8") as f:
        examples = [json.loads(line) for line in f if line.strip()]

    print(f"=== Training Data Analysis: {path} ===\n")
    print(f"Total examples: {len(examples)}")

    # Global stats
    lengths = []
    weights = []
    for ex in examples:
        asst = ex["conversations"][2]["content"]
        lengths.append(len(asst))
        weights.append(ex.get("weight", 1.0))

    print(f"Avg response length: {sum(lengths) // len(lengths)} chars")
    print(f"Min: {min(lengths)}, Max: {max(lengths)}")
    print(f"Under 200: {sum(1 for l in lengths if l < 200)}")
    print(f"200-1000: {sum(1 for l in lengths if 200 <= l <= 1000)}")
    print(f"1000-1500: {sum(1 for l in lengths if 1000 < l <= 1500)}")
    print(f"1500-2000: {sum(1 for l in lengths if 1500 < l <= 2000)}")
    print(f"Over 2000: {sum(1 for l in lengths if l > 2000)}")
    print(f"Weight range: {min(weights):.2f} - {max(weights):.2f}")
    print()

    # Per-example analysis
    keep = []
    remove = []
    truncate = []

    for i, ex in enumerate(examples):
        user = ex["conversations"][1]["content"]
        asst = ex["conversations"][2]["content"]
        weight = ex.get("weight", 1.0)
        length = len(asst)

        # Count identity keywords
        text = (user + " " + asst).lower()
        id_hits = sum(1 for kw in IDENTITY_KEYWORDS if kw in text)

        # Count code blocks
        code_blocks = asst.count("```")

        # Classify
        reason = None
        action = "keep"

        # Removal candidates
        if code_blocks >= 4 and id_hits < 2:
            action = "remove"
            reason = f"heavy code ({code_blocks} blocks), low identity ({id_hits} hits)"
        elif length > 2000 and id_hits < 3:
            action = "remove"
            reason = f"very long ({length} chars), low identity ({id_hits} hits)"
        elif weight < 0.65:
            action = "remove"
            reason = f"low weight ({weight:.2f})"
        elif length > 1500 and id_hits < 2:
            action = "remove"
            reason = f"long ({length} chars), minimal identity ({id_hits} hits)"

        # Truncation candidates
        elif length > 1500 and id_hits >= 3:
            action = "truncate"
            reason = f"long ({length} chars) but has identity ({id_hits} hits)"

        preview = user[:80].replace("\n", " ").encode("ascii", "replace").decode()

        if action == "remove":
            remove.append(i)
        elif action == "truncate":
            truncate.append(i)
        else:
            keep.append(i)

        # Print detailed line for the report
        flag = {"keep": " ", "remove": "X", "truncate": "T"}[action]
        print(
            f"[{flag}] Line {i:3d} | {length:5d} chars | "
            f"id:{id_hits:2d} | w:{weight:.2f} | "
            f"code:{code_blocks:1d} | {preview}"
        )
        if reason:
            print(f"       -> {action}: {reason}")

    print(f"\n=== Summary ===")
    print(f"Keep:     {len(keep)}")
    print(f"Remove:   {len(remove)}")
    print(f"Truncate: {len(truncate)}")
    print()

    # Write keep_list.txt
    keep_path = path.parent.parent / "curated" / "keep_list.txt"
    keep_path.parent.mkdir(parents=True, exist_ok=True)
    with open(keep_path, "w") as f:
        f.write("# Lines to keep from existing training data\n")
        f.write(f"# Source: {path.name}\n")
        f.write(f"# Generated by analyze_training_data.py\n")
        f.write(f"# Keep: {len(keep)}, Remove: {len(remove)}, Truncate: {len(truncate)}\n")
        for idx in sorted(keep + truncate):
            f.write(f"{idx}\n")
    print(f"Keep list written to: {keep_path}")
    print(f"({len(keep) + len(truncate)} examples retained)")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python scripts/analyze_training_data.py <training_data.jsonl>")
        sys.exit(1)
    analyze(Path(sys.argv[1]))
