"""Build the final training dataset from curated data.

**ORPO mode** (2026-04-24): emits (chosen, rejected) preference pairs for
every row. `chosen` = the curated assistant content. `rejected` = base-model
counterpart from `data/curated/_rejected/{filename}` (generated by
`scripts/generate_rejecteds.py`).

Rows with `drop_reason` are skipped entirely (E6 keep_list flip).

Legacy SFT mode (weight duplication) is gone. ORPO consumes preference
strength directly via the β hyperparameter.

Output schema (per row):
    {"prompt": [...], "chosen": [...], "rejected": [...], "metadata": {...}}

Where `prompt` is the list of non-assistant turns (system, user).
`chosen` and `rejected` are each a single assistant turn [{"role":
"assistant", "content": "..."}]. TRL's ORPOTrainer accepts this
"conversational" format directly.

Usage:
    python scripts/build_training_set.py [--output data/training/YYYY-MM-DD.jsonl]
"""

import json
import random
import sys
from datetime import date
from pathlib import Path

project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root / "src"))

from svapna.consolidate.format import IDENTITY_SYSTEM_PROMPT  # noqa: E402

CURATED_DIR = project_root / "data" / "curated"
REJECTED_DIR = CURATED_DIR / "_rejected"
SEED = 42
MAX_RESPONSE_LENGTH = 1500
MIN_RESPONSE_LENGTH = 10


def get_turns(row: dict) -> list[dict]:
    """Extract messages/conversations, whichever key is used."""
    return row.get("messages") or row.get("conversations") or []


def normalize_system_prompt(turns: list[dict]) -> list[dict]:
    """Replace `_SYSTEM_PROMPT_` placeholder with canonical system prompt.

    Leaves real system prompts (including ritual mantra openings) intact.
    Returns a new list; doesn't mutate input.
    """
    out = []
    for msg in turns:
        if msg.get("role") == "system" and msg.get("content") == "_SYSTEM_PROMPT_":
            out.append({"role": "system", "content": IDENTITY_SYSTEM_PROMPT})
        else:
            out.append(dict(msg))
    return out


def load_curated_with_rejecteds() -> tuple[list[dict], dict]:
    """Load every curated JSONL, pair with rejected sidecar, skip drops.

    Returns (preference_pairs, stats). Each preference_pair is:
        {
          "prompt": [system, user, ...],
          "chosen": [{"role":"assistant","content":...}],
          "rejected": [{"role":"assistant","content":...}],
          "metadata": {"category":..., "source_file":..., "source_row":...}
        }
    """
    pairs: list[dict] = []
    stats = {
        "files_scanned": 0,
        "rows_loaded": 0,
        "rows_dropped_by_reason": {},
        "rows_missing_rejected": 0,
        "rows_too_short": 0,
        "rows_too_long_truncated": 0,
    }

    for src in sorted(CURATED_DIR.glob("*.jsonl")):
        if src.parent != CURATED_DIR:
            continue
        stats["files_scanned"] += 1

        with open(src, encoding="utf-8") as f:
            src_rows = [json.loads(line) for line in f if line.strip()]

        rej_path = REJECTED_DIR / src.name
        rej_rows: list[dict] = []
        if rej_path.exists():
            with open(rej_path, encoding="utf-8") as f:
                rej_rows = [json.loads(line) for line in f if line.strip()]

        for i, row in enumerate(src_rows):
            # Drop-reason gate
            reason = row.get("drop_reason")
            if reason:
                stats["rows_dropped_by_reason"].setdefault(reason, 0)
                stats["rows_dropped_by_reason"][reason] += 1
                continue

            src_turns = get_turns(row)
            if len(src_turns) < 3:
                continue

            # Need a rejected counterpart
            if i >= len(rej_rows):
                stats["rows_missing_rejected"] += 1
                continue
            rej_turns = get_turns(rej_rows[i])
            if len(rej_turns) < 3:
                stats["rows_missing_rejected"] += 1
                continue

            # Normalize prompts (replace placeholder)
            src_turns = normalize_system_prompt(src_turns)

            chosen_content = src_turns[-1]["content"]
            rejected_content = rej_turns[-1]["content"]

            # Length gates
            if len(chosen_content) < MIN_RESPONSE_LENGTH:
                stats["rows_too_short"] += 1
                continue
            if len(chosen_content) > MAX_RESPONSE_LENGTH:
                # Truncate at sentence boundary
                trunc = chosen_content[:MAX_RESPONSE_LENGTH]
                cut = max(trunc.rfind("."), trunc.rfind("\n"))
                if cut > MAX_RESPONSE_LENGTH // 2:
                    chosen_content = chosen_content[:cut + 1]
                else:
                    chosen_content = trunc
                stats["rows_too_long_truncated"] += 1
            # Rejected length: cap similarly but don't require min
            if len(rejected_content) > MAX_RESPONSE_LENGTH:
                trunc = rejected_content[:MAX_RESPONSE_LENGTH]
                cut = max(trunc.rfind("."), trunc.rfind("\n"))
                rejected_content = rejected_content[:cut + 1] if cut > MAX_RESPONSE_LENGTH // 2 else trunc

            prompt = src_turns[:-1]  # system + user turns
            pair = {
                "prompt": prompt,
                "chosen": [{"role": "assistant", "content": chosen_content}],
                "rejected": [{"role": "assistant", "content": rejected_content}],
                "metadata": {
                    "category": row.get("category", "conversation"),
                    "source_file": src.name,
                    "source_row": i,
                    "weight": row.get("weight", 1.0),
                },
            }
            pairs.append(pair)
            stats["rows_loaded"] += 1

    return pairs, stats


def main() -> None:
    output_path = None
    if len(sys.argv) > 2 and sys.argv[1] == "--output":
        output_path = Path(sys.argv[2])
    if output_path is None:
        output_path = project_root / "data" / "training" / f"{date.today()}.jsonl"

    print("=== Svapna Training Set Builder — ORPO mode ===\n")

    pairs, stats = load_curated_with_rejecteds()
    print(f"Files scanned: {stats['files_scanned']}")
    print(f"Rows loaded: {stats['rows_loaded']}")
    print(f"Rows dropped by reason:")
    for reason, count in sorted(stats["rows_dropped_by_reason"].items()):
        print(f"  {reason}: {count}")
    print(f"Rows missing rejected sidecar: {stats['rows_missing_rejected']}")
    print(f"Rows truncated (too long): {stats['rows_too_long_truncated']}")
    print(f"Rows skipped (too short): {stats['rows_too_short']}")

    # Category breakdown
    cats: dict[str, int] = {}
    for p in pairs:
        c = p["metadata"].get("category", "conversation")
        cats[c] = cats.get(c, 0) + 1
    print("\nCategory breakdown (preference pairs):")
    for c, n in sorted(cats.items()):
        print(f"  {c}: {n}")

    # Length stats
    chosen_lens = [len(p["chosen"][0]["content"]) for p in pairs]
    rejected_lens = [len(p["rejected"][0]["content"]) for p in pairs]
    print(f"\nLength stats:")
    print(f"  Chosen   avg {sum(chosen_lens) // max(len(chosen_lens), 1)} "
          f"min {min(chosen_lens, default=0)} max {max(chosen_lens, default=0)}")
    print(f"  Rejected avg {sum(rejected_lens) // max(len(rejected_lens), 1)} "
          f"min {min(rejected_lens, default=0)} max {max(rejected_lens, default=0)}")

    # Shuffle
    random.seed(SEED)
    random.shuffle(pairs)

    # Write
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        for p in pairs:
            f.write(json.dumps(p, ensure_ascii=False) + "\n")

    print(f"\nWrote {len(pairs)} preference pairs to {output_path}")
    print(f"Size: {output_path.stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    main()
