#!/usr/bin/env python
"""Build a sprite atlas from a directory of PNGs + a JSON manifest.

Reads `embodiment/sprites/<atlas_name>/<atlas_name>.json` plus the PNGs
it references, and emits `embodiment/firmware/include/atlas_<name>.h`
with a stable enum, a flat pixel pool (RGB565), and a metadata table.

Format spec lives in `docs/plans/embodiment-phase2-design-2026-05-02.md`.

Usage:
    python scripts/build_atlas.py embodiment/sprites/test_atlas
    python scripts/build_atlas.py embodiment/sprites/narada_face
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from PIL import Image

# Reserved RGB565 key meaning "transparent". 0xF81F = pure magenta
# (R=31, G=0, B=31). Any source pixel that maps to this value is
# nudged to 0xF83F (R=31, G=1, B=31) before emit, so we never emit
# the key for a pixel that wasn't intended transparent.
TRANSPARENT_KEY = 0xF81F
TRANSPARENT_REPLACEMENT = 0xF83F


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def png_to_rgb565(path: Path) -> tuple[int, int, list[int]]:
    """Load a PNG, return (w, h, rgb565_pixels). Pixels with alpha < 128
    or pure-magenta RGB are emitted as TRANSPARENT_KEY."""
    img = Image.open(path).convert("RGBA")
    w, h = img.size
    out: list[int] = []
    for r, g, b, a in img.getdata():
        if a < 128 or (r >= 248 and g < 8 and b >= 248):
            out.append(TRANSPARENT_KEY)
            continue
        v = rgb888_to_rgb565(r, g, b)
        if v == TRANSPARENT_KEY:
            v = TRANSPARENT_REPLACEMENT
        out.append(v)
    return w, h, out


def c_identifier(name: str) -> str:
    """Normalize a frame name into a C-friendly all-caps identifier."""
    return re.sub(r"[^A-Z0-9]+", "_", name.upper()).strip("_")


def emit_header(
    out_path: Path,
    atlas_name: str,
    enum_prefix: str,
    frames: list[dict],
    pixel_pool: list[int],
    anchor: str,
) -> None:
    enum_type = "".join(p.capitalize() for p in atlas_name.split("_")) + "Frame"
    var_prefix = atlas_name.lower()
    lines: list[str] = []
    lines.append(f"// Auto-generated by scripts/build_atlas.py from")
    lines.append(f"// embodiment/sprites/{atlas_name}/")
    lines.append(f"// Atlas: {atlas_name}, anchor: {anchor}, frames: {len(frames)}")
    lines.append(f"// Pixel pool: {len(pixel_pool)} px ({len(pixel_pool) * 2} bytes)")
    lines.append("// DO NOT EDIT — regenerate from the source.")
    lines.append("")
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append(
        "// Reserved key — pixels with this value are skipped by the blit"
    )
    lines.append("// (treated as transparent). 0xF81F = pure magenta.")
    lines.append(f"static constexpr uint16_t ATLAS_TRANSPARENT = 0x{TRANSPARENT_KEY:04X};")
    lines.append("")
    lines.append("// Frame IDs. Stable across builds for a fixed source set.")
    lines.append(f"enum {enum_type} : uint16_t {{")
    for i, fr in enumerate(frames):
        lines.append(f"  {enum_prefix}_{c_identifier(fr['name'])} = {i},")
    lines.append(f"  {enum_prefix}_FRAME_COUNT = {len(frames)}")
    lines.append("};")
    lines.append("")
    lines.append("struct AtlasFrame {")
    lines.append("  uint16_t w;")
    lines.append("  uint16_t h;")
    lines.append("  int16_t  ox;")
    lines.append("  int16_t  oy;")
    lines.append("  uint32_t pixel_offset;")
    lines.append("};")
    lines.append("")
    lines.append(
        f"static const AtlasFrame {var_prefix}_frames[{len(frames)}] = {{"
    )
    for fr in frames:
        lines.append(
            f"  {{ {fr['w']}, {fr['h']}, {fr['ox']}, {fr['oy']}, "
            f"{fr['pixel_offset']} }},  // {fr['name']}"
        )
    lines.append("};")
    lines.append("")
    lines.append(
        f"static const uint32_t {var_prefix}_pixel_count = {len(pixel_pool)};"
    )
    lines.append("")
    lines.append(
        f"static const uint16_t {var_prefix}_pixels[{len(pixel_pool)}] = {{"
    )
    # Wrap at 16 entries per line to keep the file diffable.
    for chunk_start in range(0, len(pixel_pool), 16):
        chunk = pixel_pool[chunk_start : chunk_start + 16]
        lines.append("  " + ", ".join(f"0x{p:04X}" for p in chunk) + ",")
    lines.append("};")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def build_atlas(atlas_dir: Path) -> Path:
    atlas_name = atlas_dir.name
    manifest_path = atlas_dir / f"{atlas_name}.json"
    if not manifest_path.exists():
        raise SystemExit(f"manifest not found: {manifest_path}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    enum_prefix = manifest.get("enum_prefix") or "".join(
        w[0].upper() for w in atlas_name.split("_")
    )
    anchor = manifest.get("anchor", "top_left")

    # Sort by frame name for stable IDs.
    frames_in = sorted(manifest["frames"], key=lambda f: f["name"])

    pixel_pool: list[int] = []
    frames_out: list[dict] = []
    for fr in frames_in:
        png_path = atlas_dir / fr["file"]
        w, h, pixels = png_to_rgb565(png_path)
        ox = int(fr.get("ox", 0))
        oy = int(fr.get("oy", 0))
        frames_out.append(
            {
                "name": fr["name"],
                "w": w,
                "h": h,
                "ox": ox,
                "oy": oy,
                "pixel_offset": len(pixel_pool),
            }
        )
        pixel_pool.extend(pixels)

    out_path = (
        atlas_dir.parent.parent
        / "firmware"
        / "include"
        / f"atlas_{atlas_name}.h"
    )
    emit_header(out_path, atlas_name, enum_prefix, frames_out, pixel_pool, anchor)
    return out_path


def main() -> None:
    if len(sys.argv) != 2:
        print("usage: python scripts/build_atlas.py <atlas_dir>")
        sys.exit(1)
    atlas_dir = Path(sys.argv[1]).resolve()
    if not atlas_dir.is_dir():
        raise SystemExit(f"not a directory: {atlas_dir}")
    out = build_atlas(atlas_dir)
    print(f"wrote {out}")
    print(f"  atlas: {atlas_dir.name}")


if __name__ == "__main__":
    main()
