#!/usr/bin/env python
"""Encode a directory of PNG frames as one RLE-compressed sandhi.

Format: per-frame stream of (count: u8, color: u16 big-endian) pairs,
terminated by a single 0 byte. Pixels with the same color in scan
order are run-length-coded; runs longer than 255 split into multiple
pairs. RGB565, magenta-key transparency NOT supported (sandhis are
opaque full-screen transitions).

Usage:
    python scripts/build_sandhi.py <name> <frames_dir> [--fps 30]

Inputs: <frames_dir>/frame_NNN.png (sorted lexicographically).
Output: embodiment/firmware/include/sandhi_<name>.h with the asset
and its metadata.

Format spec: docs/plans/embodiment-phase3-sandhi-2026-05-02.md
"""
from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def png_to_rgb565(path: Path, expected_w: int, expected_h: int) -> list[int]:
    img = Image.open(path).convert("RGB")
    if img.size != (expected_w, expected_h):
        raise SystemExit(
            f"{path}: size {img.size} != expected ({expected_w},{expected_h})"
        )
    return [rgb888_to_rgb565(r, g, b) for (r, g, b) in img.getdata()]


def rle_encode(pixels: list[int]) -> bytes:
    """Encode pixels as (count, color_be) runs. End marker = single 0 byte."""
    out = bytearray()
    i = 0
    n = len(pixels)
    while i < n:
        c = pixels[i]
        run = 1
        while i + run < n and pixels[i + run] == c and run < 255:
            run += 1
        out.append(run)
        out.append((c >> 8) & 0xFF)
        out.append(c & 0xFF)
        i += run
    out.append(0)  # end-of-frame
    return bytes(out)


def emit_header(out_path: Path, name: str, frames_rle: list[bytes],
                width: int, height: int, fps: int) -> None:
    upper = name.upper()
    var = name.lower()
    pixel_pool = bytearray()
    offsets: list[int] = []
    for fr in frames_rle:
        offsets.append(len(pixel_pool))
        pixel_pool.extend(fr)
    total_size = len(pixel_pool)

    lines: list[str] = []
    lines.append(f"// Auto-generated by scripts/build_sandhi.py")
    lines.append(f"// Sandhi: {name}, {len(frames_rle)} frames, "
                 f"{width}x{height} @ {fps} fps")
    lines.append(f"// Compressed payload: {total_size} bytes "
                 f"({total_size / 1024:.1f} KB)")
    lines.append(f"// Uncompressed equiv: "
                 f"{len(frames_rle) * width * height * 2} bytes")
    lines.append("// DO NOT EDIT — regenerate from the source PNGs.")
    lines.append("")
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append(f"static constexpr uint16_t SANDHI_{upper}_WIDTH = {width};")
    lines.append(f"static constexpr uint16_t SANDHI_{upper}_HEIGHT = {height};")
    lines.append(f"static constexpr uint16_t SANDHI_{upper}_FPS = {fps};")
    lines.append(
        f"static constexpr uint16_t SANDHI_{upper}_FRAME_COUNT = "
        f"{len(frames_rle)};"
    )
    lines.append("")
    lines.append(
        f"static const uint32_t sandhi_{var}_offsets["
        f"{len(offsets)}] = {{"
    )
    for chunk_start in range(0, len(offsets), 8):
        chunk = offsets[chunk_start:chunk_start + 8]
        lines.append("  " + ", ".join(str(o) for o in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append(
        f"static const uint8_t sandhi_{var}_rle[{total_size}] = {{"
    )
    for chunk_start in range(0, total_size, 16):
        chunk = pixel_pool[chunk_start:chunk_start + 16]
        lines.append(
            "  " + ", ".join(f"0x{b:02X}" for b in chunk) + ","
        )
    lines.append("};")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def build_sandhi(name: str, frames_dir: Path, fps: int) -> Path:
    pngs = sorted(frames_dir.glob("frame_*.png"))
    if not pngs:
        raise SystemExit(f"no frame_*.png files in {frames_dir}")
    first = Image.open(pngs[0]).convert("RGB")
    width, height = first.size
    frames_rle: list[bytes] = []
    total_uncompressed = 0
    for png in pngs:
        pixels = png_to_rgb565(png, width, height)
        rle = rle_encode(pixels)
        frames_rle.append(rle)
        total_uncompressed += len(pixels) * 2
    out = (
        frames_dir.parent.parent
        / "firmware"
        / "include"
        / f"sandhi_{name}.h"
    )
    emit_header(out, name, frames_rle, width, height, fps)
    total_compressed = sum(len(f) for f in frames_rle)
    ratio = total_uncompressed / total_compressed
    print(
        f"wrote {out}\n"
        f"  frames: {len(pngs)} @ {width}x{height} {fps} fps\n"
        f"  rle: {total_compressed / 1024:.1f} KB "
        f"(vs uncompressed {total_uncompressed / 1024:.1f} KB, "
        f"{ratio:.1f}x)"
    )
    return out


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("name", help="Sandhi name, e.g. enter_interior")
    p.add_argument("frames_dir", type=Path,
                   help="Directory of frame_NNN.png files")
    p.add_argument("--fps", type=int, default=30)
    args = p.parse_args()
    build_sandhi(args.name, args.frames_dir, args.fps)


if __name__ == "__main__":
    main()
