#!/usr/bin/env python
"""Generate placeholder sprites for embodiment perf verification.

Phase 1 of the embodiment scenes/sprites work — see
docs/plans/embodiment-scenes-and-sprites-2026-05-02.md.

Outputs a C header with 8 distinct 32x32 RGB565 sprites. Each sprite has
a solid-color background and a frame-number digit drawn in white pixels
(quick visual check that the renderer is selecting the right frame).
No aesthetic constraint — these exist to exercise the sprite blit
pipeline before any real art is commissioned.

Usage:
    python scripts/gen_test_sprites.py
    # writes to embodiment/firmware/include/test_sprites.h
"""
from __future__ import annotations

from pathlib import Path

SPRITE_SIZE = 32
NUM_SPRITES = 8

# 8 visually-distinct background colors (hue-stepped).
# Stored as RGB888; converted to RGB565 below.
COLORS_RGB = [
    (200, 50, 50),    # 0 red
    (200, 130, 30),   # 1 orange
    (200, 200, 30),   # 2 yellow
    (60, 180, 60),    # 3 green
    (30, 180, 180),   # 4 cyan
    (40, 80, 200),    # 5 blue
    (140, 50, 200),   # 6 purple
    (200, 50, 140),   # 7 pink
]

# 5x7 pixel digit glyphs (1 = white pixel, 0 = bg color). Drawn at frame
# center so the eye can read which sprite is which without zooming.
DIGITS = {
    0: ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
    1: ["00100", "01100", "00100", "00100", "00100", "00100", "01110"],
    2: ["01110", "10001", "00001", "00010", "00100", "01000", "11111"],
    3: ["01110", "10001", "00001", "00110", "00001", "10001", "01110"],
    4: ["00010", "00110", "01010", "10010", "11111", "00010", "00010"],
    5: ["11111", "10000", "11110", "00001", "00001", "10001", "01110"],
    6: ["00110", "01000", "10000", "11110", "10001", "10001", "01110"],
    7: ["11111", "00001", "00010", "00100", "01000", "01000", "01000"],
}


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    """RGB888 → RGB565 packed uint16. Big-endian on the wire is what
    most ST7789/ILI9xxx panels expect; the framebuffer in ESPHome's
    BITS_16 mode stores high byte first, low byte second per pixel."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def make_sprite(idx: int) -> list[int]:
    """Return SPRITE_SIZE*SPRITE_SIZE RGB565 pixels for sprite `idx`."""
    bg = rgb888_to_rgb565(*COLORS_RGB[idx])
    fg = rgb888_to_rgb565(255, 255, 255)
    pixels = [bg] * (SPRITE_SIZE * SPRITE_SIZE)

    # Draw a 1-pixel border so the sprite edges are visible at runtime.
    for x in range(SPRITE_SIZE):
        pixels[x] = fg
        pixels[(SPRITE_SIZE - 1) * SPRITE_SIZE + x] = fg
    for y in range(SPRITE_SIZE):
        pixels[y * SPRITE_SIZE] = fg
        pixels[y * SPRITE_SIZE + SPRITE_SIZE - 1] = fg

    # Draw the digit at center, scaled 2x (so 5x7 → 10x14). Center at
    # (SPRITE_SIZE/2, SPRITE_SIZE/2) means top-left at (11, 9).
    glyph = DIGITS[idx]
    x0, y0 = (SPRITE_SIZE - 10) // 2, (SPRITE_SIZE - 14) // 2
    for gy, row in enumerate(glyph):
        for gx, ch in enumerate(row):
            if ch == "1":
                # 2x scale
                for dy in range(2):
                    for dx in range(2):
                        px = x0 + gx * 2 + dx
                        py = y0 + gy * 2 + dy
                        pixels[py * SPRITE_SIZE + px] = fg
    return pixels


def emit_header(path: Path) -> None:
    lines: list[str] = []
    lines.append("// Auto-generated by scripts/gen_test_sprites.py")
    lines.append("// DO NOT EDIT — regenerate from the script.")
    lines.append("//")
    lines.append("// 8 placeholder sprites for embodiment perf verification.")
    lines.append("// Each sprite is 32x32 pixels, RGB565, packed as uint16_t.")
    lines.append("// Frame number is drawn in white at sprite center.")
    lines.append("")
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append(f"static constexpr int TEST_SPRITE_SIZE = {SPRITE_SIZE};")
    lines.append(f"static constexpr int TEST_SPRITE_COUNT = {NUM_SPRITES};")
    lines.append("")
    lines.append(
        f"static const uint16_t test_sprites"
        f"[{NUM_SPRITES}][{SPRITE_SIZE * SPRITE_SIZE}] = {{"
    )
    for i in range(NUM_SPRITES):
        sprite = make_sprite(i)
        lines.append(f"    // sprite {i}")
        lines.append("    {")
        for row_start in range(0, SPRITE_SIZE * SPRITE_SIZE, SPRITE_SIZE):
            row = sprite[row_start : row_start + SPRITE_SIZE]
            row_str = ", ".join(f"0x{p:04X}" for p in row)
            lines.append(f"        {row_str},")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    out = Path(__file__).resolve().parent.parent / "embodiment" / "firmware" / "include" / "test_sprites.h"
    emit_header(out)
    bytes_total = NUM_SPRITES * SPRITE_SIZE * SPRITE_SIZE * 2
    print(f"wrote {out}")
    print(f"  {NUM_SPRITES} sprites × {SPRITE_SIZE}×{SPRITE_SIZE} RGB565")
    print(f"  flash footprint: {bytes_total} bytes ({bytes_total / 1024:.1f} KB)")
